name: homekitchen_customer_mobile
description: An app for those who love to eat family flavors
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  flutter_picker: ^2.1.0
  bottom_picker: ^2.1.0
  google_fonts: ^6.1.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  intl: ^0.18.1
  dio: ^5.3.3
  go_router: ^11.1.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  curved_navigation_bar: ^1.0.3
  flutter_screenutil: ^5.9.0
  firebase_messaging: ^14.6.9
  google_sign_in: ^6.1.5
  country_picker: ^2.0.21
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  pinput: ^3.0.1
  image_picker: ^1.0.4
  http: ^1.1.0
  google_maps_flutter: ^2.5.0
  firebase_analytics: ^10.6.0
  flutter_local_notifications: ^16.1.0
  flutter_native_splash: ^2.3.4
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.13.1

flutter:
  # generate: true
  uses-material-design: true
  assets:
    - assets/images/
# flutter_intl:
#   enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo_x3.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/Logo_x3.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/Logo_x3.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/Logo_x3.png"
