name: homekitchen_customer_mobile
description: An app for those who love to eat family flavors
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  flutter_picker: ^2.1.0
  bottom_picker: ^2.1.0
  google_fonts: ^6.1.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  intl: ^0.18.1
  dio: ^5.3.3
  go_router: ^11.1.1
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  curved_navigation_bar: ^1.0.3
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
