version: 2.1

jobs:
  build:
    working_directory: ~/my_flutter_app
    docker:
      - image: ghcr.io/cirruslabs/flutter:3.13.9

    environment:
      FLUTTER_VERSION: 3.13.9

    steps:
      - checkout

      # Restore Flutter cache (you can also cache it to speed up builds)
      - restore_cache:
          keys:
            - flutter-cache-{{ checksum "pubspec.yaml" }}

      # Download and install Flutter
      - run:
          name: Install Flutter
          command: |
            curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.9-stable.tar.xz
            tar xf flutter.tar.xz
            export PATH="$HOME/flutter/bin:$PATH"
            flutter precache
            flutter pub get

      # Save Flutter cache
      - save_cache:
          key: flutter-cache-{{ checksum "pubspec.yaml" }}
          paths:
            - ~/.pub-cache
            - ~/.pub

      # Build the Flutter app
      - run:
          name: Build Android APK
          command: flutter build apk

      # Create iOS artifacts (for Mac)
      # - run:
      #     name: Build iOS artifacts
      #     command: |
      #       flutter build ios
      #       mkdir -p ios/build/iphoneos/Runner.app/Frameworks
      #       flutter build ios --release --no-codesign

      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
          destination: flutter-apps

      - store_artifacts:
          path: ios/build/iphoneos/Runner.app
          destination: flutter-apps

workflows:
  version: 2
  build:
    jobs:
      - build
